name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.REMOTE_USER }}
          script: |
            cd ${{ secrets.REMOTE_TARGET }}

            php artisan down

            git fetch origin main
            git reset --hard origin/main

            composer install --no-interaction --prefer-dist --optimize-autoloader

            # Migrate database
            php artisan migrate --force

            php artisan auth:clear-resets
            php artisan cache:clear
            # configuration cache file
            php artisan config:clear
            php artisan config:cache
            # events and listeners
            php artisan event:clear
            php artisan event:cache
            # route
            php artisan route:clear
            php artisan route:cache
            # view
            php artisan view:clear
            php artisan view:cache
            # bootstrap files
            php artisan optimize:clear
            php artisan optimize

            service php8.0-fpm reload

            chown -R :www-data .
            chmod -R 777 database storage bootstrap/cache
            systemctl restart laravel-queue

            php artisan up
